Tarea 1 · Conjunto de datos de muestra

In [ ]:
import os
import shutil

# 1. Crear la carpeta 'datos'
os.makedirs("datos", exist_ok=True)

# 2. Lista de nuestros archivos
archivos = [
    "calificaciones.csv",
    "pm25_sintetico.csv",
    "productos.csv",
    "sucursales.json",
    "ventas_sucio.csv"
]

# 3. Mover cada archivo a la carpeta 'datos/' automáticamente
for archivo in archivos:
    if os.path.exists(archivo):
        shutil.move(archivo, f"datos/{archivo}")
        print(f"📁 Movido exitosamente: {archivo} -> datos/{archivo}")

print("\n ¡Todo listo y organizado en la carpeta 'datos'! Ya podemos empezar con las tareas.")

📁 Movido exitosamente: calificaciones.csv -> datos/calificaciones.csv
📁 Movido exitosamente: pm25_sintetico.csv -> datos/pm25_sintetico.csv
📁 Movido exitosamente: productos.csv -> datos/productos.csv
📁 Movido exitosamente: sucursales.json -> datos/sucursales.json
📁 Movido exitosamente: ventas_sucio.csv -> datos/ventas_sucio.csv

 ¡Todo listo y organizado en la carpeta 'datos'! Ya podemos empezar con las tareas.

In [ ]:
import os
import pandas as pd
import numpy as np

np.random.seed(42)
n = 50

ids_productos = [f"PROD_{i:03d}" for i in range(1, n + 1)]
nombres = [f"Artículo Local {i}" for i in range(1, n + 1)]
stock = np.random.randint(10, 300, size=n)
precio = np.round(np.random.uniform(10.0, 250.0, size=n), 2)
fechas = pd.date_range(start="2026-01-01", periods=n, freq="D")
categorias = np.random.choice(["Abarrotes", "Papelería", "Bebidas", "Snacks"], size=n)
activo = np.random.choice([True, False], size=n, p=[0.85, 0.15])

df_muestra = pd.DataFrame({
    "producto_id": ids_productos,
    "nombre_producto": nombres,
    "stock": stock,
    "precio": precio,
    "ultima_actualizacion": fechas,
    "categoria": categorias,
    "activo": activo
})

df_muestra["categoria"] = df_muestra["categoria"].astype("category")

print("--- Primeras filas del dataset de muestra ---")
display(df_muestra.head())

print("\n--- Tipos de datos originales ---")
print(df_muestra.dtypes)

os.makedirs("datos", exist_ok=True)
csv_path = "datos/muestra_tienda.csv"
parquet_path = "datos/muestra_tienda.parquet"

df_muestra.to_csv(csv_path, index=False)
df_muestra.to_parquet(parquet_path, index=False)

df_leido_parquet = pd.read_parquet(parquet_path)
print("\n--- Tipos de datos recuperados desde Parquet ---")
print(df_leido_parquet.dtypes)

tamanio_csv = os.path.getsize(csv_path)
tamanio_parquet = os.path.getsize(parquet_path)

print(f"\nTamaño en disco (CSV): {tamanio_csv} bytes")
print(f"Tamaño en disco (Parquet): {tamanio_parquet} bytes")
print(f"Parquet es {tamanio_csv / tamanio_parquet:.2f} veces más compacto que el CSV.")

--- Primeras filas del dataset de muestra ---

,producto_id,nombre_producto,stock,precio,ultima_actualizacion,categoria,activo
0,PROD_001,Artículo Local 1,112,146.25,2026-01-01,Snacks,True
1,PROD_002,Artículo Local 2,280,17.52,2026-01-02,Abarrotes,True
2,PROD_003,Artículo Local 3,116,212.15,2026-01-03,Bebidas,True
3,PROD_004,Artículo Local 4,81,117.94,2026-01-04,Bebidas,True
4,PROD_005,Artículo Local 5,198,104.84,2026-01-05,Snacks,True

--- Tipos de datos originales ---
producto_id                     object
nombre_producto                 object
stock                            int64
precio                         float64
ultima_actualizacion    datetime64[ns]
categoria                     category
activo                            bool
dtype: object

--- Tipos de datos recuperados desde Parquet ---
producto_id                     object
nombre_producto                 object
stock                            int64
precio                         float64
ultima_actualizacion    datetime64[ns]
categoria                     category
activo                            bool
dtype: object

Tamaño en disco (CSV): 3223 bytes
Tamaño en disco (Parquet): 6351 bytes
Parquet es 0.51 veces más compacto que el CSV.

¿Qué hicimos y por qué?
Para esta práctica creamos una tabla de prueba con 50 registros que incluía 6 tipos de datos diferentes (texto, números enteros, decimales, fechas, categorías y booleanos). La idea principal era comparar cómo se comportan dos formatos muy conocidos al guardarlos en la computadora: el clásico CSV y el formato avanzado Apache Parquet.

¿Qué ventajas notamos al usar Parquet?
No se pierden los tipos de datos: Nos dimos cuenta de que cuando guardas un archivo en CSV, al volver a abrirlo pandas a veces ya no sabe si una columna era fecha o categoría y te lo convierte todo en texto plano.

¿En qué caso NO nos convendría usar Parquet?
Un detalle importante es que Parquet no se recomendaría si necesitamos abrir el archivo rápidamente para revisarlo a simple vista en un bloc de notas

Tarea 2 · Consultas sobre ventas

In [ ]:
import pandas as pd
from google.colab import files

print("Sube tu archivo 'ventas_sucio.csv':")
uploaded = files.upload()

# Leemos el archivo que acabas de subir
nombre_archivo = list(uploaded.keys())[0]
df_ventas = pd.read_csv(nombre_archivo)

print("\n--- Primeras 5 filas del dataset ---")
display(df_ventas.head())

print("\n--- Información general y nulos ---")
df_ventas.info()

print("\n--- Conteo de valores nulos por columna ---")
print(df_ventas.isnull().sum())

Sube tu archivo 'ventas_sucio.csv':

Saving ventas_sucio.csv to ventas_sucio.csv

--- Primeras 5 filas del dataset ---

   venta_id       fecha sucursal_id producto_id cantidad precio_unitario
0      1001  2026-01-14         S03        P003      7.0          $30.37
1      1002  2026-04-08         S02        P009     10.0           34.41
2      1003  2026-06-15         S02        P012      1.0           40.98
3      1004  2026-04-13         S01        P009      7.0          $32.03
4      1004  2026-04-13         S01        P009      7.0          $32.03

--- Información general y nulos ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 612 entries, 0 to 611
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   venta_id         612 non-null    int64
 1   fecha            612 non-null    object
 2   sucursal_id      612 non-null    object
 3   producto_id      612 non-null    object
 4   cantidad         586 non-null    object
 5   precio_unitario  594 non-null    object
dtypes: int64(1), object(5)
memory usage: 28.8+ KB

--- Conteo de valores nulos por columna ---
venta_id            0
fecha               0
sucursal_id         0
producto_id         0
cantidad           26
precio_unitario    18
dtype: int64

In [ ]:
df_ventas['precio_unitario'] = df_ventas['precio_unitario'].astype(str).str.replace('$', '').str.strip()
df_ventas['precio_unitario'] = pd.to_numeric(df_ventas['precio_unitario'], errors='coerce')

df_ventas['cantidad'] = pd.to_numeric(df_ventas['cantidad'], errors='coerce')

df_ventas['cantidad'].fillna(df_ventas['cantidad'].median(), inplace=True)
df_ventas['precio_unitario'].fillna(df_ventas['precio_unitario'].median(), inplace=True)

print("--- Conteo de nulos después de limpiar ---")
print(df_ventas.isnull().sum())

--- Conteo de nulos después de limpiar ---
venta_id           0
fecha              0
sucursal_id        0
producto_id        0
cantidad           0
precio_unitario    0
dtype: int64

/tmp/ipykernel_427/1798427406.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ventas['cantidad'].fillna(df_ventas['cantidad'].median(), inplace=True)
/tmp/ipykernel_427/1798427406.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ventas['precio_unitario'].fillna(df_ventas['precio_unitario'].median(), inplace=True)



1.   ¿Cuántas ventas hay de los productos P001 y P010? Usa isin.

In [ ]:
import pandas as pd

df_original = pd.read_csv("ventas_sucio.csv")

filtro_p1 = df_original[df_original['producto_id'].isin(['P001', 'P010'])]

print(f"Total de ventas de P001 y P010: {len(filtro_p1)}")
display(filtro_p1.head())

Total de ventas de P001 y P010: 111

    venta_id       fecha sucursal_id producto_id cantidad precio_unitario
19      1018  2026-01-28         S01        P010      6.0           79.31
34      1032  2026-03-05         S03        P001      180           36.22
35      1033  2026-04-25         S02        P001      5.0           37.33
39      1037  2026-05-01         S02        P001      2.0           38.25
41      1039  2026-06-14         S02        P010     10.0           79.41

2.   Muestra las ventas de enero de 2026 de la sucursal S01. Tip: filtra la fecha como texto con .str.startswith("2026-01").

In [ ]:
print("=== Ventas de enero de 2026 de la sucursal S01 ===")

filtro_p2 = df_original[
    (df_original['sucursal_id'] == 'S01') &
    (df_original['fecha'].astype(str).str.startswith('2026-01'))
]

print(f"Total de registros encontrados: {len(filtro_p2)}")
display(filtro_p2.head())

=== Ventas de enero de 2026 de la sucursal S01 ===
Total de registros encontrados: 20

    venta_id       fecha sucursal_id producto_id cantidad precio_unitario
19      1018  2026-01-28         S01        P010      6.0           79.31
33      1031  2026-01-01         S01        P009     10.0           32.54
51      1048  2026-01-14         S01        P009      5.0            31.8
60      1057  2026-01-12         S01        P008      7.0            46.8
70      1067  2026-01-24         S01        P010     1 pz           76.98

3. Ordena las ventas por producto_id y luego por venta_id.

In [ ]:
print("=== Ventas ordenadas por producto_id y venta_id ===")

df_ordenado = df_original.sort_values(by=['producto_id', 'venta_id'])

display(df_ordenado.head(10))

=== Ventas ordenadas por producto_id y venta_id ===

     venta_id       fecha sucursal_id producto_id cantidad precio_unitario
34       1032  2026-03-05         S03        P001      180           36.22
35       1033  2026-04-25         S02        P001      5.0           37.33
39       1037  2026-05-01         S02        P001      2.0           38.25
58       1055  2026-02-02         S02        P001      7.0           39.48
59       1056  2026-01-16         S04        P001      8.0            38.6
79       1076  2026-04-08         S03        P001      6.0            37.1
80       1077  2026-04-04         S01        P001      4.0           38.62
86       1083  2026-06-06         S03        P001      8.0            37.7
119      1116  2026-05-03         S01        P001      3.0           36.99
132      1129  2026-04-17         S02        P001      5.0          $38.21

4. Intenta filtrar cantidad > 5. Describe el error que obtienes y explica su causa.

In [ ]:
print("=== Filtrar cantidad > 5 ===")

try:
    filtro_error = df_original[df_original['cantidad'] > 5]
    print("Filtro aplicado (si no marcó error).")
except Exception as e:
    print("¡Error obtenido con éxito!\n")
    print(type(e).__name__, ":", e)

=== Filtrar cantidad > 5 ===
¡Error obtenido con éxito!

TypeError : '>' not supported between instances of 'str' and 'int'

Descripción del error:
Se obtiene un TypeError al intentar ejecutar la comparación mayor que (> 5) en la columna cantidad.   
Causa:
Se debe a que la columna cantidad se cargó originalmente como un tipo de dato de texto o cadena, debido a la presencia de valores nulos, espacios o caracteres mezclados, lo cual impide que Pandas realice operaciones o comparaciones matemáticas directas con números enteros como el 5.

In [ ]:
Reflexión (media cuartilla): ¿qué problemas de calidad detectaste solo con estas consultas?

Al realizar estas consultas me di cuenta de que trabajar con datos sin limpiar es bastante complicado porque te topas con varios problemas de calidad desde el inicio. Por ejemplo, cuando intenté hacer el filtro con los números me salió un error de tipos de datos, lo que pasa porque la información viene mal guardada como texto y no te deja hacer operaciones matemáticas directas. También noté que hay valores faltantes en varias columnas, lo que significa que la información está incompleta y puede alterar cualquier resultado o conteo si no se revisa bien. En pocas palabras, te das cuenta de que los datos reales siempre vienen muy desordenados, con formatos distintos y errores de captura, por lo que es obligatorio hacer una buena limpieza y validación antes de empezar a analizar cualquier cosa.

# Tarea 3. Diagnóstico y Limpieza
## Lectura y diagnóstico inicial

In [1]:
# Importamos pandas para manipular los datos.
import pandas as pd

# Importamos NumPy para operaciones numéricas.
import numpy as np

# El CSV debe encontrarse dentro de la carpeta datos.
# Leemos el CSV y conservamos los datos originales.
ventas_originales = pd.read_csv("datos/ventas_sucio.csv")

# Creamos una copia para mantener compatibles los diagnósticos
# que ya escribimos utilizando la variable ventas.
ventas = ventas_originales.copy()

# Confirmamos que el archivo se cargó correctamente.
print("Archivo ventas_sucio.csv cargado correctamente.")

# Mostramos sus dimensiones: filas y columnas.
print("Dimensiones del dataset:", ventas.shape)

print("INFORMACIÓN GENERAL")
ventas.info()

print("VALORES NULOS")
print(ventas.isnull().sum())

print("DUPLICADOS")
print(ventas.duplicated().sum())

print("PRIMERAS FILAS")

display(ventas.head())

# Generamos un resumen estadístico de las columnas.
# include="all" permite incluir columnas numéricas y categóricas.
print("RESUMEN ESTADÍSTICO INICIAL")

display(ventas.describe(include="all"))

Archivo ventas_sucio.csv cargado correctamente.
Dimensiones del dataset: (612, 6)
INFORMACIÓN GENERAL
<class 'pandas.DataFrame'>
RangeIndex: 612 entries, 0 to 611
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   venta_id         612 non-null    int64
 1   fecha            612 non-null    str
 2   sucursal_id      612 non-null    str
 3   producto_id      612 non-null    str
 4   cantidad         586 non-null    str
 5   precio_unitario  594 non-null    str
dtypes: int64(1), str(5)
memory usage: 43.8 KB
VALORES NULOS
venta_id            0
fecha               0
sucursal_id         0
producto_id         0
cantidad           26
precio_unitario    18
dtype: int64
DUPLICADOS
12
PRIMERAS FILAS

   venta_id       fecha sucursal_id producto_id cantidad precio_unitario
0      1001  2026-01-14         S03        P003      7.0          $30.37
1      1002  2026-04-08         S02        P009     10.0           34.41
2      1003  2026-06-15         S02        P012      1.0           40.98
3      1004  2026-04-13         S01        P009      7.0          $32.03
4      1004  2026-04-13         S01        P009      7.0          $32.03

RESUMEN ESTADÍSTICO INICIAL

,venta_id,fecha,sucursal_id,producto_id,cantidad,precio_unitario
count,612.000000,612,612,612,586,594
unique,NaN,195,13,12,23,528
top,NaN,2026-03-27,S01,P001,5.0,18.67
freq,NaN,9,208,59,61,4
mean,1298.395425,NaN,NaN,NaN,NaN,NaN
std,173.718334,NaN,NaN,NaN,NaN,NaN
min,1001.000000,NaN,NaN,NaN,NaN,NaN
25%,1149.750000,NaN,NaN,NaN,NaN,NaN
50%,1297.500000,NaN,NaN,NaN,NaN,NaN
75%,1448.250000,NaN,NaN,NaN,NaN,NaN
max,1600.000000,NaN,NaN,NaN,NaN,NaN

## Diagnóstico de duplicados

In [2]:
# Cuenta las filas duplicadas adicionales.
print(ventas.duplicated().sum())

# Cuenta todas las filas involucradas en duplicaciones.
print(ventas.duplicated(keep=False).sum())

12
24

## Identificación de registros duplicados

In [3]:
# Identificamos todas las filas que pertenecen a grupos
# de registros duplicados, incluyendo la primera aparición.
duplicados = ventas[
    ventas.duplicated(keep=False)
]

# Ordenamos los registros por su identificador de venta.
duplicados = duplicados.sort_values("venta_id")

# Mostramos todos los registros duplicados.
display(duplicados)

     venta_id       fecha sucursal_id producto_id cantidad precio_unitario
3        1004  2026-04-13         S01        P009      7.0          $32.03
4        1004  2026-04-13         S01        P009      7.0          $32.03
7        1007  2026-06-27         S01        P002      6.0           18.67
8        1007  2026-06-27         S01        P002      6.0           18.67
29       1028  2026-05-10         S04        P007      2.0           30.04
30       1028  2026-05-10         S04        P007      2.0           30.04
48       1046  2026-06-23         S02        P007      6.0           31.56
49       1046  2026-06-23         S02        P007      6.0           31.56
170      1167  2026-03-22        S04         P003      1.0           28.99
171      1167  2026-03-22        S04         P003      1.0           28.99
185      1181  2026-01-21         S04        P004      3.0           23.95
186      1181  2026-01-21         S04        P004      3.0           23.95
194      1189  2026-04-07         S04        P007      7.0           31.76
195      1189  2026-04-07         S04        P007      7.0           31.76
202      1196  2026-06-25         S03        P007      NaN           30.69
203      1196  2026-06-25         S03        P007      NaN           30.69
290      1283  2026-04-29         S03        P005      4.0           51.11
291      1283  2026-04-29         S03        P005      4.0           51.11
331      1323  2026-01-16         S02        P011      5.0           17.17
332      1323  2026-01-16         S02        P011      5.0           17.17
335      1326  2026-02-12         S01        P010      5.0           76.82
336      1326  2026-02-12         S01        P010      5.0           76.82
578      1568  2026-05-15         S01        P001      4.0           37.03
579      1568  2026-05-15         S01        P001      4.0           37.03

## Definición de funciones reutilizables de limpieza

In [4]:
# Función para normalizar columnas de texto.
def limpiar_texto(serie):

    # Convertimos los valores a texto conservando los faltantes.
    serie = serie.astype("string")

    # Eliminamos espacios al inicio y al final.
    serie = serie.str.strip()

    # Convertimos el texto a mayúsculas.
    serie = serie.str.upper()

    # Devolvemos la columna normalizada.
    return serie


# Función para convertir valores de texto a números.
def a_numero(serie):

    # Convertimos los valores a texto conservando los faltantes.
    serie = serie.astype("string")

    # Eliminamos el símbolo monetario.
    serie = serie.str.replace("$", "", regex=False)

    # Eliminamos la abreviatura de piezas.
    serie = serie.str.replace("pz", "", regex=False)

    # Eliminamos espacios sobrantes.
    serie = serie.str.strip()

    # Convertimos a valores numéricos.
    # Los valores que no se puedan convertir quedarán como NaN.
    return pd.to_numeric(serie, errors="coerce")

## Preparamos una copia para realizar el diagnóstico
## Preparar copia sin duplicados

In [5]:
# Creamos una copia sin duplicados a partir del dataset original.
ventas_sin_duplicados = ventas_originales.drop_duplicates().copy()

# Contamos las filas que necesitan normalización,
# después de eliminar los duplicados.
filas_sucursal_limpieza = (
    ventas_sin_duplicados["sucursal_id"].astype("string")
    != limpiar_texto(ventas_sin_duplicados["sucursal_id"])
).sum()

# Mostramos los resultados.
print("Filas originales:", len(ventas))

print("Filas después de quitar duplicados:",
      len(ventas_sin_duplicados))

print("Filas que necesitan normalización de sucursal:",
      filas_sucursal_limpieza)

Filas originales: 612
Filas después de quitar duplicados: 600
Filas que necesitan normalización de sucursal: 40

## Diagnóstico de sucursales

In [6]:
# Mostramos los códigos de sucursal antes de limpiarlos.
print("SUCURSALES ANTES DE LA LIMPIEZA")

# value_counts() cuenta cuántas veces aparece cada valor.
# dropna=False incluye los valores faltantes, si existen.
display(
    ventas["sucursal_id"].value_counts(dropna=False)
)

# Contamos cuántos códigos distintos existen originalmente.
print(
    "Códigos de sucursal originales:",
    ventas["sucursal_id"].nunique()
)

# Aplicamos la función de normalización a una copia temporal.
# Todavía no modificamos el DataFrame original.
sucursales_normalizadas = limpiar_texto(
    ventas["sucursal_id"]
)

# Contamos cuántos códigos diferentes quedarían.
print(
    "Códigos después de normalizar:",
    sucursales_normalizadas.nunique()
)

# Identificamos cuántas filas cambiarían con la normalización.
filas_sucursal_afectadas = (
    ventas["sucursal_id"].astype("string")
    != sucursales_normalizadas
).sum()

print(
    "Filas que requieren normalización:",
    filas_sucursal_afectadas
)

# Mostramos los códigos normalizados y sus frecuencias.
print("SUCURSALES DESPUÉS DE NORMALIZAR")

display(
    sucursales_normalizadas.value_counts(dropna=False)
)

SUCURSALES ANTES DE LA LIMPIEZA

sucursal_id
S01      208
S02      153
S03      123
S04       87
 S02      10
S02        8
S04        7
S03        5
 S01       4
 S03       3
s01        2
S01        1
s02        1
Name: count, dtype: int64

Códigos de sucursal originales: 13
Códigos después de normalizar: 4
Filas que requieren normalización: 41
SUCURSALES DESPUÉS DE NORMALIZAR

sucursal_id
S01    215
S02    172
S03    131
S04     94
Name: count, dtype: int64[pyarrow]

### Diagnóstico de las columnas cantidad y precio_unitario

Se identificarán los valores faltantes, los formatos
inconsistentes y los registros que no pueden convertirse
correctamente a valores numéricos.

El diagnóstico se realizará sobre los 600 registros
resultantes de excluir los duplicados, sin modificar
todavía el dataset original.

In [7]:
# Seleccionamos las columnas numéricas que vamos a diagnosticar.
columnas_numericas = ["cantidad", "precio_unitario"]

# Recorremos cada columna para analizar sus problemas.
for columna in columnas_numericas:

    # Mostramos el nombre de la columna analizada.
    print(f"\nDIAGNÓSTICO DE: {columna}")

    # Obtenemos los valores originales, sin modificarlos.
    valores_originales = ventas_sin_duplicados[columna]

    # Contamos los valores faltantes originales.
    nulos_originales = valores_originales.isna().sum()

    # Convertimos temporalmente los valores a números.
    valores_convertidos = a_numero(valores_originales)

    # Contamos los valores faltantes después de convertir.
    nulos_convertidos = valores_convertidos.isna().sum()

    # Identificamos los valores no nulos que no pudieron convertirse.
    conversiones_fallidas = (
        valores_originales.notna()
        & valores_convertidos.isna()
    ).sum()

    # Identificamos valores que contienen símbolos o unidades.
    valores_con_formato = valores_originales.astype("string").str.contains(
        r"\$|pz",
        case=False,
        regex=True,
        na=False
    ).sum()

    # Mostramos los resultados del diagnóstico.
    print("Nulos originales:", nulos_originales)
    print("Nulos después de convertir:", nulos_convertidos)
    print("Conversiones fallidas:", conversiones_fallidas)
    print("Valores con símbolos o unidades:", valores_con_formato)

    # Mostramos ejemplos de valores que no pudieron convertirse.
    print("Ejemplos de conversiones fallidas:")

    display(
        valores_originales[
            valores_originales.notna()
            & valores_convertidos.isna()
        ].head(10)
    )

DIAGNÓSTICO DE: cantidad
Nulos originales: 25
Nulos después de convertir: 25
Conversiones fallidas: 0
Valores con símbolos o unidades: 13
Ejemplos de conversiones fallidas:

Series([], Name: cantidad, dtype: str)

DIAGNÓSTICO DE: precio_unitario
Nulos originales: 18
Nulos después de convertir: 18
Conversiones fallidas: 0
Valores con símbolos o unidades: 30
Ejemplos de conversiones fallidas:

Series([], Name: precio_unitario, dtype: str)

### Diagnóstico de la columna fecha

Se identificarán los formatos de fecha presentes en el dataset
y se comprobará si existen registros que no pueden convertirse
correctamente al tipo datetime.

El diagnóstico se realiza sobre los 600 registros sin duplicados.

In [8]:
# Obtenemos las fechas originales sin modificar el DataFrame.
fechas_originales = ventas_sin_duplicados["fecha"]

# Intentamos convertir las fechas con formato año-mes-día.
fechas_iso = pd.to_datetime(
    fechas_originales,
    format="%Y-%m-%d",
    errors="coerce"
)

# Intentamos convertir las fechas con formato día/mes/año.
fechas_dmy = pd.to_datetime(
    fechas_originales,
    format="%d/%m/%Y",
    errors="coerce"
)

# Combinamos ambas conversiones.
# Si la primera produjo NaT, usamos la segunda.
fechas_convertidas = fechas_iso.fillna(fechas_dmy)

# Contamos cuántas fechas pertenecen a cada formato.
cantidad_iso = fechas_iso.notna().sum()
cantidad_dmy = fechas_dmy.notna().sum()

# Identificamos fechas presentes que no pudieron convertirse.
fechas_invalidas = (
    fechas_originales.notna()
    & fechas_convertidas.isna()
).sum()

# Contamos valores faltantes originales.
fechas_nulas = fechas_originales.isna().sum()

# Mostramos los resultados.
print("DIAGNÓSTICO DE FECHAS")

print("Fechas en formato AAAA-MM-DD:", cantidad_iso)
print("Fechas en formato DD/MM/AAAA:", cantidad_dmy)
print("Fechas nulas originales:", fechas_nulas)
print("Fechas que no pudieron convertirse:", fechas_invalidas)

# Mostramos ejemplos de fechas que no pudieron convertirse.
print("\nEJEMPLOS DE FECHAS INVÁLIDAS")

display(
    fechas_originales[
        fechas_originales.notna()
        & fechas_convertidas.isna()
    ].head(10)
)

DIAGNÓSTICO DE FECHAS
Fechas en formato AAAA-MM-DD: 580
Fechas en formato DD/MM/AAAA: 20
Fechas nulas originales: 0
Fechas que no pudieron convertirse: 0

EJEMPLOS DE FECHAS INVÁLIDAS

Series([], Name: fecha, dtype: str)

## Limpieza definitiva y verificaciones

## Aplicación de la limpieza

In [9]:
# ============================================================
# TAREA 3 - LIMPIEZA DEFINITIVA DEL DATASET DE VENTAS
# ============================================================

# Creamos una copia independiente de los datos sin duplicados.
# Así conservamos intactos los DataFrames utilizados en los diagnósticos.
ventas_limpias = ventas_sin_duplicados.copy()


# ------------------------------------------------------------
# 1. NORMALIZACIÓN DE SUCURSALES
# ------------------------------------------------------------

# Eliminamos espacios sobrantes y convertimos los códigos a mayúsculas.
ventas_limpias["sucursal_id"] = limpiar_texto(
    ventas_limpias["sucursal_id"]
)


# ------------------------------------------------------------
# 2. CONVERSIÓN DE COLUMNAS NUMÉRICAS
# ------------------------------------------------------------

# Eliminamos símbolos y convertimos los precios a números.
ventas_limpias["precio_unitario"] = a_numero(
    ventas_limpias["precio_unitario"]
)

# Eliminamos unidades de texto y convertimos las cantidades a números.
ventas_limpias["cantidad"] = a_numero(
    ventas_limpias["cantidad"]
)


# ------------------------------------------------------------
# 3. CONVERSIÓN DE FECHAS
# ------------------------------------------------------------

# Convertimos las fechas usando los dos formatos detectados
# durante el diagnóstico: AAAA-MM-DD y DD/MM/AAAA.

fechas_iso_limpieza = pd.to_datetime(
    ventas_limpias["fecha"],
    format="%Y-%m-%d",
    errors="coerce"
)

fechas_dmy_limpieza = pd.to_datetime(
    ventas_limpias["fecha"],
    format="%d/%m/%Y",
    errors="coerce"
)

# Conservamos las fechas ISO válidas y completamos con las DMY.
ventas_limpias["fecha"] = fechas_iso_limpieza.fillna(
    fechas_dmy_limpieza
)


# ------------------------------------------------------------
# 4. TRATAMIENTO DE VALORES FALTANTES
# ------------------------------------------------------------

# Contamos los valores faltantes antes de imputar.
nulos_cantidad = ventas_limpias["cantidad"].isna().sum()
nulos_precio = ventas_limpias["precio_unitario"].isna().sum()


# 4.1 IMPUTACIÓN DE CANTIDAD POR PRODUCTO

# Calculamos la mediana de cantidad correspondiente a cada producto.
mediana_cantidad_producto = ventas_limpias.groupby(
    "producto_id"
)["cantidad"].transform("median")

# Redondeamos las medianas para mantener cantidades enteras.
mediana_cantidad_producto = mediana_cantidad_producto.round()

# Identificamos los casos que no pueden imputarse por producto.
sin_mediana_cantidad = (
    ventas_limpias["cantidad"].isna()
    & mediana_cantidad_producto.isna()
).sum()

# Imputamos las cantidades faltantes con la mediana de su producto.
ventas_limpias["cantidad"] = ventas_limpias["cantidad"].fillna(
    mediana_cantidad_producto
)

# Calculamos una mediana general de respaldo.
mediana_general_cantidad = round(
    ventas_limpias["cantidad"].median()
)

# Aplicamos el respaldo únicamente si quedan valores faltantes.
ventas_limpias["cantidad"] = ventas_limpias["cantidad"].fillna(
    mediana_general_cantidad
)


# 4.2 IMPUTACIÓN DE PRECIO UNITARIO POR PRODUCTO

# Calculamos la mediana del precio correspondiente a cada producto.
mediana_precio_producto = ventas_limpias.groupby(
    "producto_id"
)["precio_unitario"].transform("median")

# Identificamos los casos que no pueden imputarse por producto.
sin_mediana_precio = (
    ventas_limpias["precio_unitario"].isna()
    & mediana_precio_producto.isna()
).sum()

# Imputamos los precios faltantes con la mediana de su producto.
ventas_limpias["precio_unitario"] = ventas_limpias[
    "precio_unitario"
].fillna(mediana_precio_producto)

# Calculamos una mediana general de respaldo.
mediana_general_precio = ventas_limpias[
    "precio_unitario"
].median()

# Aplicamos el respaldo únicamente si quedan valores faltantes.
ventas_limpias["precio_unitario"] = ventas_limpias[
    "precio_unitario"
].fillna(mediana_general_precio)


# ------------------------------------------------------------
# 5. COMPROBACIÓN INICIAL DE LA LIMPIEZA
# ------------------------------------------------------------

print("RESUMEN DE LIMPIEZA")
print("Registros originales:", len(ventas_originales))
print("Registros limpios:", len(ventas_limpias))
print("Duplicados restantes:", ventas_limpias.duplicated().sum())

print("\nRESUMEN DE IMPUTACIÓN")
print("Cantidades faltantes originales:", nulos_cantidad)
print("Precios faltantes originales:", nulos_precio)

print("Cantidades imputadas con respaldo general:",
      sin_mediana_cantidad)

print("Precios imputados con respaldo general:",
      sin_mediana_precio)

print("\nNULOS DESPUÉS DE LIMPIAR")
print(ventas_limpias.isnull().sum())

print("\nTIPOS DE DATOS")
print(ventas_limpias.dtypes)

print("\nSUCURSALES NORMALIZADAS")
print(ventas_limpias["sucursal_id"].value_counts())

print("\nPRIMERAS FILAS DEL DATASET LIMPIO")
display(ventas_limpias.head())

RESUMEN DE LIMPIEZA
Registros originales: 612
Registros limpios: 600
Duplicados restantes: 0

RESUMEN DE IMPUTACIÓN
Cantidades faltantes originales: 25
Precios faltantes originales: 18
Cantidades imputadas con respaldo general: 0
Precios imputados con respaldo general: 0

NULOS DESPUÉS DE LIMPIAR
venta_id           0
fecha              0
sucursal_id        0
producto_id        0
cantidad           0
precio_unitario    0
dtype: int64

TIPOS DE DATOS
venta_id                    int64
fecha              datetime64[us]
sucursal_id                string
producto_id                   str
cantidad                  Float64
precio_unitario           Float64
dtype: object

SUCURSALES NORMALIZADAS
sucursal_id
S01    211
S02    170
S03    129
S04     90
Name: count, dtype: int64[pyarrow]

PRIMERAS FILAS DEL DATASET LIMPIO

   venta_id      fecha sucursal_id producto_id  cantidad  precio_unitario
0      1001 2026-01-14         S03        P003       7.0            30.37
1      1002 2026-04-08         S02        P009      10.0            34.41
2      1003 2026-06-15         S02        P012       1.0            40.98
3      1004 2026-04-13         S01        P009       7.0            32.03
5      1005 2026-02-16         S04        P011       1.0            17.24

## Verificar que no existan cantidades fraccionarias, cantidades no positivas o precios no positivos.

In [10]:
# ============================================================
# TAREA 3 - VALIDACIÓN DE VALORES LIMPIOS
# ============================================================

# Identificamos cantidades que tienen parte decimal.
cantidades_fraccionarias = (
    ventas_limpias["cantidad"] % 1 != 0
).sum()

# Identificamos cantidades iguales o menores que cero.
cantidades_no_positivas = (
    ventas_limpias["cantidad"] <= 0
).sum()

# Identificamos precios iguales o menores que cero.
precios_no_positivos = (
    ventas_limpias["precio_unitario"] <= 0
).sum()

# Identificamos fechas que no pudieron convertirse.
fechas_invalidas_finales = (
    ventas_limpias["fecha"].isna().sum()
)

# Mostramos los resultados.
print("VALIDACIÓN DE VALORES LIMPIOS")

print("Cantidades fraccionarias:", cantidades_fraccionarias)
print("Cantidades no positivas:", cantidades_no_positivas)
print("Precios no positivos:", precios_no_positivos)
print("Fechas inválidas:", fechas_invalidas_finales)

# Comprobamos que los datos cumplen estas condiciones.
assert cantidades_fraccionarias == 0, "Existen cantidades fraccionarias"
assert cantidades_no_positivas == 0, "Existen cantidades no positivas"
assert precios_no_positivos == 0, "Existen precios no positivos"
assert fechas_invalidas_finales == 0, "Existen fechas inválidas"

print("\nTodas las validaciones de valores fueron superadas.")

VALIDACIÓN DE VALORES LIMPIOS
Cantidades fraccionarias: 0
Cantidades no positivas: 0
Precios no positivos: 0
Fechas inválidas: 0

Todas las validaciones de valores fueron superadas.

### Bitácora de limpieza de datos

Se documentaron los problemas de calidad identificados en el conjunto de datos de ventas, incluyendo registros duplicados, inconsistencias en los códigos de sucursal, formatos numéricos, valores faltantes y formatos de fecha.

Para los valores faltantes de `cantidad` y `precio_unitario`, se utilizó la mediana correspondiente a cada producto, con el propósito de conservar las características particulares de sus registros. No fue necesario utilizar la mediana general de respaldo.

La siguiente tabla presenta las columnas afectadas, los problemas detectados, la cantidad de filas involucradas, las acciones correctivas y sus respectivas verificaciones.

In [11]:
# ============================================================
# TAREA 3 - BITÁCORA DE LIMPIEZA
# ============================================================

# Registramos los problemas detectados durante el diagnóstico,
# las acciones realizadas y la verificación de cada corrección.

bitacora = pd.DataFrame({
    "Columna": [
        "Todas",
        "sucursal_id",
        "cantidad",
        "precio_unitario",
        "cantidad",
        "precio_unitario",
        "fecha"
    ],

    "Problema": [
        "Registros duplicados",
        "Espacios y uso inconsistente de mayúsculas",
        "Cantidades almacenadas con unidades de texto",
        "Precios almacenados con símbolos monetarios",
        "Valores faltantes",
        "Valores faltantes",
        "Dos formatos diferentes de fecha"
    ],

    "Filas afectadas": [
        12,
        filas_sucursal_limpieza,
        13,
        30,
        nulos_cantidad,
        nulos_precio,
        cantidad_dmy
    ],

    "Acción aplicada": [
        "Eliminación de duplicados",
        "Eliminación de espacios y conversión a mayúsculas",
        "Eliminación de unidades y conversión numérica",
        "Eliminación de símbolos y conversión numérica",
        "Imputación con mediana de cantidad por producto",
        "Imputación con mediana de precio por producto",
        "Conversión a datetime"
    ],

    "Verificación": [
        "0 duplicados restantes",
        "4 sucursales normalizadas",
        "Columna numérica y sin cantidades fraccionarias",
        "Columna numérica y sin precios no positivos",
        "0 valores nulos en cantidad",
        "0 valores nulos en precio_unitario",
        "0 fechas inválidas"
    ]
})

print("BITÁCORA DE LIMPIEZA")
display(bitacora)

BITÁCORA DE LIMPIEZA

,Columna,Problema,Filas afectadas,Acción aplicada,Verificación
0,Todas,Registros duplicados,12,Eliminación de duplicados,0 duplicados restantes
1,sucursal_id,Espacios y uso inconsistente de mayúsculas,40,Eliminación de espacios y conversión a mayúsculas,4 sucursales normalizadas
2,cantidad,Cantidades almacenadas con unidades de texto,13,Eliminación de unidades y conversión numérica,Columna numérica y sin cantidades fraccionarias
3,precio_unitario,Precios almacenados con símbolos monetarios,30,Eliminación de símbolos y conversión numérica,Columna numérica y sin precios no positivos
4,cantidad,Valores faltantes,25,Imputación con mediana de cantidad por producto,0 valores nulos en cantidad
5,precio_unitario,Valores faltantes,18,Imputación con mediana de precio por producto,0 valores nulos en precio_unitario
6,fecha,Dos formatos diferentes de fecha,20,Conversión a datetime,0 fechas inválidas

## Verificaciones

In [12]:
# ============================================================
# TAREA 3 - VERIFICACIONES FINALES
# ============================================================

# 1. Comprobamos que se conservaron los 600 registros esperados.
assert len(ventas_limpias) == 600, \
    "El número de registros no es el esperado."

# 2. Comprobamos que no existen duplicados.
assert ventas_limpias.duplicated().sum() == 0, \
    "Existen registros duplicados."

# 3. Comprobamos que no existen valores faltantes.
assert ventas_limpias.isna().sum().sum() == 0, \
    "Existen valores faltantes."

# 4. Comprobamos que cantidad y precio sean numéricos.
assert pd.api.types.is_numeric_dtype(ventas_limpias["cantidad"]), \
    "La columna cantidad no es numérica."

assert pd.api.types.is_numeric_dtype(ventas_limpias["precio_unitario"]), \
    "La columna precio_unitario no es numérica."

# 5. Comprobamos que fecha sea de tipo datetime.
assert pd.api.types.is_datetime64_any_dtype(ventas_limpias["fecha"]), \
    "La columna fecha no es de tipo datetime."

# 6. Comprobamos que existan exactamente cuatro sucursales.
assert set(ventas_limpias["sucursal_id"].unique()) == {
    "S01", "S02", "S03", "S04"
}, "Los códigos de sucursal no son los esperados."

# 7. Comprobamos que las cantidades sean enteras y positivas.
assert ((ventas_limpias["cantidad"] % 1) == 0).all(), \
    "Existen cantidades fraccionarias."

assert (ventas_limpias["cantidad"] > 0).all(), \
    "Existen cantidades no positivas."

# 8. Comprobamos que todos los precios sean positivos.
assert (ventas_limpias["precio_unitario"] > 0).all(), \
    "Existen precios no positivos."

# 9. Comprobamos que los identificadores de producto estén presentes.
assert ventas_limpias["producto_id"].notna().all(), \
    "Existen identificadores de producto faltantes."

print("TODAS LAS VERIFICACIONES FINALES FUERON SUPERADAS.")
print("Dataset listo para exportarse a Parquet.")

TODAS LAS VERIFICACIONES FINALES FUERON SUPERADAS.
Dataset listo para exportarse a Parquet.

## Exportar y verificar el archivo Parquet

In [13]:
# ============================================================
# TAREA 3 - EXPORTACIÓN Y VERIFICACIÓN DEL ARCHIVO PARQUET
# ============================================================

# Importamos Path para trabajar con carpetas y archivos.
from pathlib import Path

# Definimos la carpeta donde guardaremos los resultados.
carpeta_resultados = Path("resultados")

# Creamos la carpeta si todavía no existe.
carpeta_resultados.mkdir(parents=True, exist_ok=True)

# Definimos la ruta completa del archivo de salida.
ruta_parquet = carpeta_resultados / "ventas_limpias.parquet"

# Guardamos el DataFrame limpio en formato Parquet.
# index=False evita guardar el índice de pandas como columna adicional.
ventas_limpias.to_parquet(ruta_parquet, index=False)

# Comprobamos que el archivo exista físicamente.
assert ruta_parquet.is_file(), "No se generó el archivo Parquet."

print("Archivo generado correctamente:", ruta_parquet)

# Volvemos a leer el archivo para verificar su contenido.
ventas_verificacion = pd.read_parquet(ruta_parquet)

# Comprobamos que tenga las mismas dimensiones.
assert ventas_verificacion.shape == ventas_limpias.shape, \
    "Las dimensiones del archivo no coinciden."

# Comprobamos que los datos guardados sean iguales a los originales limpios.
pd.testing.assert_frame_equal(
    ventas_verificacion.reset_index(drop=True),
    ventas_limpias.reset_index(drop=True)
)

print("\nVERIFICACIÓN DEL ARCHIVO PARQUET")
print("Dimensiones:", ventas_verificacion.shape)
print("Duplicados:", ventas_verificacion.duplicated().sum())
print("Valores nulos:", ventas_verificacion.isna().sum().sum())

print("\nEl archivo Parquet se guardó y verificó correctamente.")

Archivo generado correctamente: resultados\ventas_limpias.parquet

VERIFICACIÓN DEL ARCHIVO PARQUET
Dimensiones: (600, 6)
Duplicados: 0
Valores nulos: 0

El archivo Parquet se guardó y verificó correctamente.